### ISSUE TITLE
show_pff.py can't read some recent files

### ISSUE THREAD

**Issue by liuweiseu** [panoseti/panoseti#137]
show_pff.py can read the data files we got last week, but can't read data file we got tonight.
```
(base) nico@dell1u00:~/panoseti/control$ ./show_pff.py /home/nico/data/obs_Lick.start_2023-02-08T05:02:27Z.runtype_1pix.pffd/start_2023-02-08T05:02:42Z.dp_ph1024.bpp_2.module_1.seqno_0.pff 
Traceback (most recent call last):
  File "/home/nico/panoseti/control/./show_pff.py", line 139, in <module>
    main()
  File "/home/nico/panoseti/control/./show_pff.py", line 133, in main
    [min, max] = image_quantiles.get_quantiles(
  File "/home/nico/panoseti/control/../util/image_quantiles.py", line 23, in get_quantiles
    values = get_values(file, img_size, bytes_per_pixel)
  File "/home/nico/panoseti/control/../util/image_quantiles.py", line 11, in get_values
    x = pff.read_json(fin)
  File "/home/nico/panoseti/control/../util/pff.py", line 13, in read_json
    raise Exception('read_json(): expected {, got', c)
Exception: ('read_json(): expected {, got', b'')

```

**Comment by liuweiseu** [comment]
Nico pointed out the issue was caused by a bug in pff.py.

It's fixed in this commit(906a5593c89c59b299d73cca1632da512427cfc1).
